# Sentiment Analysis on IMDB Movie Review Dataset 

###  Import dependies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from random import choice
import math

### Preprocessing
> Try to get all train reviews in one train_reviews file and all text reviews in one test_reviews file (similarly for labels in train_labels, test_labes). This makes easier to gather set of all the words in all reviews and one hot encoded data.

While moving the data into new files they are also stored in a randomized way to remove any kind of bias.

#### For Training

In [2]:
os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone')
with open('train_reviews.txt', 'wb') as train_reviews:
    with open('train_labels.txt', 'wb') as train_labels:
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\train\\pos')
        pos = ['pos\\'+i for i in os.listdir()]
        pos_index = 0
        max_pos_index = len(pos)
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\train\\neg')
        neg = ['neg\\'+i for i in os.listdir()]
        neg_index = 0
        max_neg_index = len(neg)
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\train')
        for _ in range(max_pos_index + max_neg_index):
            
            if pos_index == max_pos_index:
                pos_or_neg = 0
                pos_complete = 1
            elif neg_index == max_neg_index:
                pos_or_neg = 1
                neg_complete = 1
            else:
                pos_or_neg = choice([0, 1])
                
            if pos_or_neg:
                with open(pos[pos_index], 'rb') as f:
                    review = f.read() + '\n'.encode()
                    train_reviews.write(review)
                    train_labels.write('1\n'.encode())
                pos_index += 1
            else:
                with open(neg[neg_index], 'rb') as f:
                    review = f.read() + '\n'.encode()
                    train_reviews.write(review)
                    train_labels.write('0\n'.encode())
                neg_index += 1

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Piyush\\3_DeepLearning\\Capstone'

#### For Testing

In [3]:
os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone')
with open('test_reviews.txt', 'wb') as test_reviews:
    with open('test_labels.txt', 'wb') as test_labels:
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\test\\pos')
        pos = ['pos\\'+i for i in os.listdir()]
        pos_index = 0
        max_pos_index = len(pos)
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\test\\neg')
        neg = ['neg\\'+i for i in os.listdir()]
        neg_index = 0
        max_neg_index = len(neg)
        
        os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone\\aclImdb\\test')
        for _ in range(max_pos_index + max_neg_index):
            
            if pos_index == max_pos_index:
                pos_or_neg = 0
                pos_complete = 1
            elif neg_index == max_neg_index:
                pos_or_neg = 1
                neg_complete = 1
            else:
                pos_or_neg = choice([0, 1])
                
            if pos_or_neg:
                with open(pos[pos_index], 'rb') as f:
                    review = f.read() + '\n'.encode()
                    test_reviews.write(review)
                    test_labels.write('1\n'.encode())
                pos_index += 1
            else:
                with open(neg[neg_index], 'rb') as f:
                    review = f.read() + '\n'.encode()
                    test_reviews.write(review)
                    test_labels.write('0\n'.encode())
                neg_index += 1

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Piyush\\3_DeepLearning\\Capstone'

## Read the Data and Preprocess

### Read the train and test data

In [4]:
# Go to main directory
os.chdir('C:\\Users\\Piyush\\3_DeepLearning\\Capstone')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Piyush\\3_DeepLearning\\Capstone'

In [5]:
# read train and test data
with open('train_reviews.txt', 'rb') as f:
    reviews = f.read().decode().lower()
with open('train_labels.txt', 'rb') as f:
    labels = f.read().decode().lower()
with open('test_reviews.txt', 'rb') as f:
    test_reviews = f.read().decode().lower()
with open('test_labels.txt', 'rb') as f:
    test_labels = f.read().decode().lower()

### Remove Punctuations from the text

In [6]:
from string import punctuation
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [7]:
# remove punctuation
punctuation = '!"#$%&()*+,./:;<=>?@[\]^`{|}~'
reviews = ''.join([i for i in reviews if i not in punctuation])
test_reviews = ''.join([i for i in test_reviews if i not in punctuation])

# Split the text into individual reviews.
reviews = reviews.split('\n')
test_reviews = test_reviews.split('\n')

# Join all the reviews but with space as joining character in place of '\n'.
reviews_continuous = ' '.join(reviews)
test_reviews_continuous = ' '.join(test_reviews)

# Split text into individual words.
reviews_words = reviews_continuous.split()
test_reviews_words = test_reviews_continuous.split()

### Encoding of Words

In [8]:
print(len(reviews_words))

5833231


In [9]:
from collections import Counter

# Building a dictionary to map words with integers(in a sorted order of usage).
count = Counter(reviews_words + test_reviews_words)
sorted_count = sorted(count, key = count.get, reverse = True)
sorted_count_dict = {word:i for i, word in enumerate(sorted_count, 1)}

preprocessed_reviews = []
preprocessed_test_reviews = []

for review, test_review in zip(reviews, test_reviews):
    preprocessed_reviews.append([sorted_count_dict[word] for word in review.split()])
    preprocessed_test_reviews.append([sorted_count_dict[word] for word in test_review.split()])

print('Total number of different words: ', len(sorted_count_dict))
print('\nExamples of preprocessed data: ', preprocessed_reviews[:1], preprocessed_test_reviews[:1], sep = '\n')

Total number of different words:  203683

Examples of preprocessed data: 
[[33189, 323, 6, 3, 1062, 215, 8, 2023, 29, 1, 164, 59, 14, 46, 78, 6302, 41, 378, 122, 138, 14, 5113, 53, 4643, 153, 7, 1, 4114, 5999, 462, 69, 5, 254, 11, 33189, 64942, 2054, 6, 72, 2465, 5, 620, 70, 6, 5113, 1, 29480, 5, 1929, 10378, 1, 5567, 1432, 35, 67, 64, 206, 142, 63, 1155, 64943, 24601, 1, 38599, 4, 1, 213, 863, 30, 3081, 69, 4, 1, 5454, 9, 651, 2, 63, 1432, 50, 9, 203, 1, 395, 7, 61, 3, 1421, 3249, 740, 5, 3523, 185, 1, 378, 9, 1176, 13412, 29, 323, 3, 355, 367, 3489, 144, 137, 5, 9451, 28, 4, 124, 5113, 1421, 2581, 5, 33189, 323, 9, 509, 11, 105, 1530, 4, 53, 643, 102, 11, 33189, 323, 6, 226, 7814, 48, 3, 2271, 11, 8, 205]]
[[9, 404, 2, 203, 10, 17, 234, 317, 100, 108, 31821, 5, 31, 3, 169, 348, 4, 1772, 637, 951, 11, 9, 13, 5654, 5, 64, 8, 84, 34, 48, 9, 651, 4, 10170, 10419, 27, 13, 60, 471, 5, 80, 215, 9, 13, 362, 10419, 250, 1, 110, 4, 3577, 17078, 52, 74, 2, 1583, 8226, 250, 1191, 8626, 15, 138, 

### Encoding of Labels

In [10]:
labels = labels.split('\n')
test_labels = test_labels.split('\n')

labels = np.array([1 if label == '1' else 0 for label in labels])
test_labels = np.array([1 if label == '1' else 0 for label in test_labels])

**Remove zero length reviews**

In [11]:
non_zero_index = [i for i, review in enumerate(preprocessed_reviews) if len(review) != 0]
non_zero_index_test = [i for i, review in enumerate(preprocessed_test_reviews) if len(review) != 0]

preprocessed_reviews = [preprocessed_reviews[i] for i in non_zero_index]
labels = np.array([labels[i] for i in non_zero_index])

preprocessed_test_reviews = [preprocessed_test_reviews[i] for i in non_zero_index_test]
test_labels = np.array([test_labels[i] for i in non_zero_index_test])

## Padding

1. We need to standardize review lengths. To find that length we take approximately the average length of all reviews as standard length.

2. A function pad_it is defined, which returns an array that contains the padded data(with 0) or shortened data(depending on the length of data), of a standard size, that we'll pass to the network.

In [12]:
def pad_it(data, length):
    
    features = np.zeros((len(data), length), dtype=int)
    for i, row in enumerate(data):
        features[i, -len(row):] = np.array(row)[:length]
    
    return features

In [13]:
total_length = 0
for i in preprocessed_reviews:
    total_length += len(i)
avg_length = total_length / len(preprocessed_reviews)
review_length = math.ceil(avg_length / 50) * 50
print("Standard length to be used: ", review_length)

Standard length to be used:  250


In [14]:
features = pad_it(preprocessed_reviews, review_length)
features_test = pad_it(preprocessed_test_reviews, review_length)
print('Example of padded data')
print(features[:10, :10])

Example of padded data
[[    0     0     0     0     0     0     0     0     0     0]
 [31200    38 87732    14   725 16374  3428    44    75    32]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [ 3806 24602   515    14     3  3403   167  8778 12375  1522]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   50     9    13   117    53   797   529    69   331     5]]


## Split train data into train and validation data

In [15]:
validation_fraction = 0.2

# Split the data
train_length = len(features)*(1 - validation_fraction)
train_length = int(train_length)
train_X, train_y = features[:train_length], labels[:train_length]
validation_X, validation_y = features[train_length:], labels[train_length:]
test_X, test_y = features_test, test_labels

print('DATASETS \nTrain\t\t{0}\nValidation\t{1}\nTest\t\t{2}'.format(train_X.shape, validation_X.shape, test_X.shape, sep = '\n'))

DATASETS 
Train		(20000, 250)
Validation	(5000, 250)
Test		(25000, 250)


## Creating Dataloaders and Batches

    TensorDataset and DataLoader from torch.utils.data can be used for this task.

In [16]:
# import additional dependencies
import torch
from torch.utils.data import TensorDataset, DataLoader

In [17]:
# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_X), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(validation_X), torch.from_numpy(validation_y))
test_data = TensorDataset(torch.from_numpy(test_X), torch.from_numpy(test_y))


# create dataloaders
batch_size = 50
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

## Create Benchmark Model

A Naive Bayes based sentiment classifier is be used as benchmark model.

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics

In [19]:
train_X_bench, train_y_bench = reviews[:25000], labels[:25000]
test_X_bench, test_y_bench = test_reviews[:25000], test_y[:25000]

In [20]:
vectorizer = CountVectorizer()

In [21]:
train_features = vectorizer.fit_transform([i for i in train_X_bench])
test_features = vectorizer.transform([i for i in test_X_bench])

In [22]:
nb = MultinomialNB()
nb.fit(train_features[:len(train_y_bench)], [int(r) for r in train_y_bench])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
predictions = nb.predict(test_features)

In [24]:
accuracy = sum(np.equal(predictions, test_y_bench)) / len(predictions) * 100
print("Multinomial Naive Bayes model accuracy: {0}".format(accuracy))

Multinomial Naive Bayes model accuracy: 81.624


## Create the Network

In [25]:
# Check for gpu
gpu_available = torch.cuda.is_available()
if (gpu_available):
    print("Training on GPU")
else:
    print("Training on CPU")

Training on GPU


In [26]:
import torch.nn as nn

class Sentiment_Analysis_Network(nn.Module):
    
    def __init__(self, words_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob = 0.5):
        super(Sentiment_Analysis_Network, self).__init__()
        
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        self.embedding_dim = embedding_dim
        self.words_size = words_size
        self.drop_prob = drop_prob
        
        self.embedding = nn.Embedding(self.words_size, self.embedding_dim)
        self.lstm = nn.LSTM(self.embedding_dim, self.hidden_dim, self.n_layers, dropout = self.drop_prob, batch_first = True)
        self.dropout = nn.Dropout(self.drop_prob)
        self.fc = nn.Linear(self.hidden_dim, self.output_size)
        self.sig = nn.Sigmoid()
        
    def forward(self, x, hidden):
        
        batch_size = x.size(0)
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        out = self.dropout(lstm_out)
        out = self.fc(out)
        out = self.sig(out)
        
        out = out.view(batch_size, - 1)
        out = out[:, -1]
        
        return out, hidden
    
    def initialize_hidden_layer(self, batch_size):
        weight = next(self.parameters()).data
        
        if (gpu_available):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden

### Define the parameters

In [31]:
words_size = len(count) + 1
output_size = 1
embedding_dim = 100
hidden_dim = 256
n_layers = 2

net = Sentiment_Analysis_Network(words_size, output_size, embedding_dim, hidden_dim, n_layers, 0.4)

print(net)

Sentiment_Analysis_Network(
  (embedding): Embedding(203684, 100)
  (lstm): LSTM(100, 256, num_layers=2, batch_first=True, dropout=0.4)
  (dropout): Dropout(p=0.4)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


## Train the Network

> Hyperparameters and other components of neural networks choosen:
    1. Loss : Binary Cross Entropy Loss
    2. lr (learning rate) : kept small
    3. epochs : kept moderate
    4. clip (maximum gradient value) : in-between 1 to 5
    5. optimizer : Adam

In [32]:
# learning rate
lr = 0.001

In [33]:
# loss and optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr = lr)

In [34]:
epochs = 5
clip = 5
print_every = 200
counter = 0

if gpu_available:
    net.cuda()
    
net.train()

for epoch in range(epochs):
    hiddens = net.initialize_hidden_layer(batch_size)
    
    for inputs, labels in train_loader:
        counter += 1
        
        if (gpu_available):
            inputs, labels = inputs.cuda(), labels.cuda()
            hiddens = tuple([each.data for each in hiddens])

        net.zero_grad()

        output, hiddens = net(inputs, hiddens)

        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        if counter % print_every == 0:
            val_hidden = net.initialize_hidden_layer(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                val_hidden = tuple([each.data for each in val_hidden])

                if (gpu_available):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_hidden = net(inputs, val_hidden)
                val_loss = criterion(output.squeeze(), labels.float())
                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}\t".format(epoch + 1),
                      "Step: {}\t".format(counter),
                      "Loss: {:.6f}\t".format(loss.item()),
                      "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1	 Step: 100	 Loss: 0.619762	 Val Loss: 0.682943
Epoch: 1	 Step: 200	 Loss: 0.635037	 Val Loss: 0.659172
Epoch: 1	 Step: 300	 Loss: 0.658900	 Val Loss: 0.669557
Epoch: 1	 Step: 400	 Loss: 0.440803	 Val Loss: 0.592388
Epoch: 2	 Step: 500	 Loss: 0.562420	 Val Loss: 0.616970
Epoch: 2	 Step: 600	 Loss: 0.618525	 Val Loss: 0.542491
Epoch: 2	 Step: 700	 Loss: 0.464774	 Val Loss: 0.489873
Epoch: 2	 Step: 800	 Loss: 0.673399	 Val Loss: 0.690893
Epoch: 3	 Step: 900	 Loss: 0.696897	 Val Loss: 0.622874
Epoch: 3	 Step: 1000	 Loss: 0.560164	 Val Loss: 0.501646
Epoch: 3	 Step: 1100	 Loss: 0.454314	 Val Loss: 0.524874
Epoch: 3	 Step: 1200	 Loss: 0.427792	 Val Loss: 0.652841
Epoch: 4	 Step: 1300	 Loss: 0.357920	 Val Loss: 0.449767
Epoch: 4	 Step: 1400	 Loss: 0.321248	 Val Loss: 0.465765
Epoch: 4	 Step: 1500	 Loss: 0.349105	 Val Loss: 0.435598
Epoch: 4	 Step: 1600	 Loss: 0.369470	 Val Loss: 0.432479
Epoch: 5	 Step: 1700	 Loss: 0.127740	 Val Loss: 0.417446
Epoch: 5	 Step: 1800	 Loss: 0.278519	 Va

## Test the Network

> Metric used for evaluation : Accuracy

In [35]:
test_losses = []
correct_count = 0

hiddens = net.initialize_hidden_layer(batch_size)

net.eval()
for inputs, labels in test_loader:
    
    hiddens =  tuple([each.data for each in hiddens])
    
    if gpu_available:
        inputs, labels = inputs.cuda(), labels.cuda()
        output, hiddens = net(inputs, hiddens)
        
        test_loss = criterion(output.squeeze(), labels.float())
        test_losses.append(test_loss.item())
        
        predictions = torch.round(output.squeeze())
        correct_tensor = predictions.eq(labels.float().view_as(predictions))
        correct = np.squeeze(correct_tensor.numpy()) if not gpu_available else np.squeeze(correct_tensor.cpu().numpy())
        correct_count += np.sum(correct)
print("Test loss: ", np.mean(test_losses))
test_accuracy = correct_count / len(test_loader.dataset)
print("Test Accuracy: ", test_accuracy)

Test loss:  0.47336623013
Test Accuracy:  0.81436
